// Maps a legend's name (subtitle) to its champion name so the dropdown
// can be searched by "Lillia" instead of "Bashful Bloom".
export const CHAMPION_BY_LEGEND_NAME = {
  'Bashful Bloom':            'Lillia',
  'Battle Mistress':          'Sivir',
  'Blade Dancer':             'Irelia',
  'Blind Monk':               'Lee Sin',
  'Bloodharbor Ripper':       'Pyke',
  'Bounty Hunter':            'Miss Fortune',
  'Chem-Baroness':            'Renata Glasc',
  'Dark Child - Starter':     'Annie',
  'Daughter of the Void':     "Kai'Sa",
  'Deceiver':                 'LeBlanc',
  'Emperor of the Sands':     'Azir',
  'Fire Below the Mountain':  'Ornn',
  'Gloomist':                 'Vex',
  'Glorious Executioner':     'Draven',
  'Grand Duelist':            'Fiora',
  'Grandmaster at Arms':      'Jax',
  'Green Father':             'Ivern',
  'Hand of Noxus':            'Darius',
  'Herald of the Arcane':     'Viktor',
  'Keeper of the Hammer':     'Poppy',
  'Lady of Luminosity - Starter': 'Lux',
  'Loose Cannon':             'Jinx',
  'Mechanized Menace':        'Rumble',
  'Might of Demacia - Starter': 'Garen',
  'Nine-Tailed Fox':          'Ahri',
  'Piltover Enforcer':        'Vi',
  'Pridestalker':             'Rengar',
  'Prodigal Explorer':        'Ezreal',
  'Purifier':                 'Lucian',
  'Radiant Dawn':             'Leona',
  'Relentless Storm':         'Volibear',
  'Scorn of the Moon':        'Diana',
  'Swift Scout':              'Teemo',
  'The Boss':                 'Sett',
  'Unforgiven':               'Yasuo',
  'Virtuoso':                 'Jhin',
  'Void Burrower':            "Rek'Sai",
  'Voidreaver':               "Kha'Zix",
  'Wuju Bladesman - Starter': 'Master Yi',
  'Wuju Master':              'Master Yi',
}
